name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all tags to compare between releases
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Configure Git Author
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Create Release
        run: pnpm release

      - name: Extract version
        id: package_version
        run: |
          version=`cat package.json | jq -r '.version'`
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'chore(release): ${{ env.VERSION }}'
          body: 'Release PR [autogenerated]' # TODO: Add changelog
          branch: release/v${{ env.VERSION }}

      - name: Push Tag
        run: |
          git push origin v$VERSION -f

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          body: 'Release v${{ env.VERSION }}' # TODO: Add changelog

      - name: Checkout to release branch
        run: git checkout release/v$VERSION

      - name: Pre-publish (lint, test, build, etc)
        run: pnpm npm:prepublish

      - name: Publish to NPM
        run: pnpm npm:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
